version: '3'
services:
  wordpress:
    depends_on:
      - db
    image: wordpress:5.0
    container_name: abp-wp
    volumes:
      - ./wp-content:/var/www/html/wp-content/
      - ./src:/var/www/html/wp-content/themes/src
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_PASSWORD: password
    ports:
      - 80:80
      - 443:443
    networks:
      - backend

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: abp-pma
    restart: always
    ports:
      - 8090:80
    environment:
      PMA_HOST: db
      PMA_ROOT_PASSWORD: password
    networks:
      - backend

  db:
    image: mysql:5.7
    container_name: abp-db
    restart: always
    volumes:
      - wp_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wp_db
    networks:
        - backend
  
networks:
  backend:
volumes:
  wp_data: